---
title: "Awesome_table"
author: "Victor Mandela"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
```

This tables theme and content summarises the difference in two time series times. It also incredibly displays the percenntage change and respective tiny awesome graphs.


```{r code for table, echo=TRUE}
library(tidyverse)
library(gt)
library(webshot)

children <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-15/kids.csv')

# Use primary and secondary school spending
school_spend <- children %>% 
  filter(variable == "PK12ed") %>% 
  select(state, year, inf_adj_perchild)

# function for plotting spark lines
plot_group <- function(name, df){
  plot_object <- 
    ggplot(data = df,
           aes(x = year, y = inf_adj_perchild)) +
    geom_line(colour = '#F3FCF0', size = 12) +
    theme_void() +
    # had to lighten background color for export to png as it was darker than table background -weird
    theme(plot.background = element_rect(fill = colorspace::lighten('#47745A', 0.12), colour =colorspace::lighten('#47745A', 0.12)),
          plot.margin = margin(0,0,0,0))
   return(plot_object)
}

# df to plot for each state
sparklines <- 
  school_spend %>% dplyr::group_by(state) %>% 
  tidyr::nest() %>% 
  dplyr::mutate(
    plot = map2(state, data, plot_group)) %>% 
  select(-data)

# prepare data for gt
# join on plotting data from above
# empty variable is needed, see:
# https://github.com/rstudio/gt/issues/152 and
# https://stackoverflow.com/questions/61741440/is-there-a-way-to-embed-a-ggplot-inage-dynamically-by-row-like-a-sparkline-usi
table_prepped <- school_spend %>% 
  filter(year %in% c(1997, 2016)) %>% 
  pivot_wider(names_from = year, values_from = inf_adj_perchild) %>% 
  mutate(percent_change = (`2016` - `1997`)/`1997`) %>% 
  inner_join(sparklines, by = "state") %>% 
  mutate(ggplot = NA)

# just keep top 10
top10 <- table_prepped %>% 
  arrange(-`2016`) %>% 
  head(10)

# table! - referenec: https://themockup.blog/posts/2020-05-16-gt-a-grammer-of-tables/
gt_table <- top10 %>% 
  dplyr::mutate(state = case_when(state == "District of Columbia" ~ "Medicine",
                                  state == "New York" ~ "Accounting, Actuaries, Finance Experts",
                                  state == "Vermont" ~ "Politics",
                                  state == "New Jersey" ~ "Marketing",
                                  state == "Connecticut" ~ "NGO and Civil Societies",
                                  state == "Alaska" ~ "Information Technology",
                                  state == "Wyoming" ~ "Lecturers",
                                  state == "Rhode Island" ~ "Media Presenters",
                                  state == "New Hampshire" ~ "Engineering",
                                  state == "Massachusetts" ~ "Pilot/ Aviation Industry"),
                `1997` = `1997`*25,
                `2016` = `2016`*25) %>% 
  gt() %>% 
  fmt_currency(
    columns = vars(`1997`, `2016`),
    decimals = 1,
    pattern = "{x}k",
    currency = "KES"
  ) %>% 
  fmt_percent(
    columns = vars(percent_change),
    decimals = 0
  ) %>% 
  cols_align(
    align = "right",
    columns = vars(`1997`, `2016`)
  ) %>% 
  cols_label(
    state = "Career",
    percent_change = "% Change",
    ggplot = "Trend",
    `1997` = "2015",
    `2016` = "2020"
  ) %>% 
  tab_source_note(html("<span style ='color:#F2AA99;'TABLE:</span> @vmandela99 | <span style='color:#F2AA99;'>DATA;</span> Career-Point")) %>% 
  tab_header(
    title = html("<br><span style='color:#F2AA99;font-size:20pt'>SEXIEST CAREERS OF THE TIME</span><br>Highest Paying Jobs In Kenya"),
    subtitle = html("Average monthly earnings in shillings paid(inflation adjusted) in the Kenya, 2015-2020<br><br><span style='color:#F2AA99;'>TOP 10 Jobs in 2020</span>")
) %>% 
  #Adjust title font
  tab_style(
    style = 
      cell_text(
        font = "Chalkduster",
        color = "#8DD8E0",
        weight = "bold",
        align = "center"),
    locations = cells_title(groups = "title")
      ) %>% 
  #Adjust subtitle font
  tab_style(
    style = cell_text(
      font = "Chalkduster",
      align = "center"),
    locations = cells_title(groups = "subtitle")
    ) %>% 
  #style header font
  gt::tab_style(
    style = cell_text(font = "Chalkduster",
                      weight = "bold",
                      color = "#FFD23F"),
    locations = cells_column_labels(gt::everything())
  ) %>% 
  #borders
  tab_style(
    style = cell_borders(
      sides = c("bottom", "top"),
      color = "white",
      weight = px(5)
    ),
    locations = cells_column_labels(columns = gt::everything())
  ) %>% 
  tab_style(
    style = cell_borders(
      sides = "bottom",
      color = "white",
      weight = px(3)),
      locations = cells_body()
  ) %>% 
  #font
  opt_table_font(font = list(c("Chalkduster"))) %>% 
  #table options
  tab_options(table.background.color = "#47745A",
              table.font.color = "#F3FCF0",
              data_row.padding = px(10)
              ) %>% 
  #rendering the sparklines - from gh reference above
  text_transform(
    locations = cells_body(columns = vars(ggplot)), #use empty cell as location
    fn = function(x){
      #insert each image into each empty cell in `ggplot`
      map(top10$plot, ggplot_image, height = px(30), aspect_ratio = 4)
    }
  ) %>% 
  cols_hide(vars(plot))

gt_table

gtsave(gt_table, "Highest_paying.png")
#gtsave(gt_table, "education_spend.html")

```

